trigger:
- main

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      imageName: 'recipe-app-api'

    steps:
    - task: Docker@2
      displayName: Build a docker image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: ./Dockerfile

    - script: |
        pip3 install setuptools
      displayName: 'Install setuptools'
      condition: succeeded()

    - script: |
        pip3 install docker-compose
      displayName: 'Install docker-compose'
      condition: succeeded()

    - script: |
        docker-compose run app sh -c "flake8"
      displayName: 'Run flake8'
      condition: succeeded()

    - script: |
        docker-compose run app sh -c "python manage.py test"
      displayName: 'Run tests'
      condition: succeeded()
